workflows:
  ios-release:
    name: iOS Release
    environment:
      flutter: stable
      xcode: latest
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.company.hrSys

    integrations:
      app_store_connect: HR

    scripts:
      - name: Get Flutter packages
        script: flutter pub get

      - name: Install CocoaPods
        script: find . -name "Podfile" -execdir pod install \;

      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles

      - name: Build iOS IPA
        script: |
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      app_store_connect:
        auth: integration