// File generated by FlutterFire CLI, merged for multi-platform use.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMN3YpVwaEvvhv_b8ZxZUOTg79WmTqvjk',
    appId: '1:737044049717:android:8ccce8d76982c269b2667c',
    messagingSenderId: '737044049717',
    projectId: 'hr-sys-fa9d3',
    storageBucket: 'hr-sys-fa9d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjtlFVwOP1gEfrHUqn7JJhucOtuSpulBQ',
    appId: '1:737044049717:ios:9aacde32b0f7f487b2667c',
    messagingSenderId: '737044049717',
    projectId: 'hr-sys-fa9d3',
    storageBucket: 'hr-sys-fa9d3.firebasestorage.app',
    iosBundleId: 'com.company.hrsysapp',
  );

  /// Web + Windows desktop use the same Firebase Web app registration.
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCx6ttrssA4FkO7CylfdiPbX_MiKYXkDU',
    appId: '1:737044049717:web:56ab1f17081a4a1cb2667c',
    messagingSenderId: '737044049717',
    projectId: 'hr-sys-fa9d3',
    authDomain: 'hr-sys-fa9d3.firebaseapp.com',
    databaseURL: 'https://hr-sys-fa9d3-default-rtdb.firebaseio.com',
    storageBucket: 'hr-sys-fa9d3.firebasestorage.app',
    measurementId: 'G-QM8GPYFR64',
  );

  static const FirebaseOptions web = windows;
}
